// The parts of provisioning that are pure functions over bytes.
//
// Split out of provision.c for one reason: host/ can build this, and the form
// parser and the URI check are where the bugs actually are. Everything here
// follows face.c's rules - no ESP-IDF header, no float, no allocation - so the
// laptop can run it.

#pragma once

#include <stdbool.h>
#include <stddef.h>

// Bounds taken from wifi_config_t, so nothing here can overflow what it feeds.
#define PL_SSID_MAX 32
#define PL_PASS_MAX 64
#define PL_URI_MAX 128

// Four digits plus the terminator. Four is not what protects the field - see
// pl_unlock_check - it is what stops a single lucky guess.
#define PL_CODE_LEN 4
#define PL_UNLOCK_MAX_TRIES 5

typedef enum {
    PL_MODE_CONNECT = 0,   // join the configured network
    PL_MODE_PROVISION,     // raise the access point
} pl_mode_t;

typedef struct {
    char code[PL_CODE_LEN + 1];
    int tries_used;
    bool unlocked;
} pl_unlock_t;

// Percent-decoding for application/x-www-form-urlencoded, where '+' is a
// space. Writes at most dst_size-1 bytes and always terminates. Returns the
// number of bytes written, not counting the terminator.
size_t pl_url_decode(const char *src, size_t src_len, char *dst, size_t dst_size);

// Pulls one field out of a form body and decodes it. Returns false when the
// field is absent; an empty value present in the body returns true with an
// empty string, which is a different thing and the caller cares.
bool pl_field(const char *body, size_t body_len, const char *name, char *out, size_t out_size);

// Shape only: scheme ws:// or wss://, a non-empty host, under PL_URI_MAX.
// Whether the server answers cannot be known from provisioning - the device is
// not on the internet yet - so a valid-looking wrong URI will be accepted.
bool pl_uri_valid(const char *uri);

pl_mode_t pl_decide(bool ssid_configured, bool hold_satisfied, bool idle_expired);

// Initialises the attempt counter around a code. The code is generated by the
// caller, because randomness needs the platform.
void pl_unlock_init(pl_unlock_t *u, const char *code);

// True when the field is unlocked, whether by this call or a previous one.
// After PL_UNLOCK_MAX_TRIES failures every further call returns false, even if
// the right code arrives - the only way to get more attempts is to hold the
// button again, which requires standing next to the device.
bool pl_unlock_check(pl_unlock_t *u, const char *entered);
